services:
  app:
    build: .
    ports:
      - "5173:4173"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - AWS_ECR_URL=${AWS_ECR_URL}
      - AWS_ECR_PASSWORD=${AWS_ECR_PASSWORD}
    restart: always
